swagger: '2.0'
info:
  description: AdminLte Laravel APis
  version: 1.0.0
  title: AdminLte Laravel Frontend API's
basePath: /api/
tags:
  - name: Login
    description: Manage Login

paths:
  /login:
    get:
      tags:
        - Login
      summary: Manage Login
      description: 'Manage Login with this API'
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
    post:
      tags:
        - Category
      summary: Create Category
      description: 'Create Category with this API'
      operationId: createCategory
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: name
          type: string
          required: true  
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      security:
        - api_key: [] 


  /register:

    post:
      tags:
        - register
      summary: Register
      description: 'Create Register with this API'
      operationId: createRegister
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: name
          type: string
          required: true
        - in: query
          name: email
          type: string
          required: true  
        - in: query
          name: password
          type: string
          required: true  
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      security:
        - api_key: [] 

  /users:
    get:
      tags:
        - Users
      summary: Manage Users
      description: 'Manage Users with this API'
      operationId: users
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      security:
        - api_key: [] 


securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header